# Servicio que analiza el texto y genera el análisis académico

import os
from groq import Groq
from models.academic_model import AcademicAnalysis, Question

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def evaluate_document(text: str, depth: str, num_questions: int) -> AcademicAnalysis:
    """
    Generates an academic analysis using Groq LLM.
    This function sends the extracted PDF text to Groq and receives:
    - Summary
    - Main ideas
    - Key concepts
    - Conclusions
    - Questions with answers
    """

    prompt = f"""
    You are an academic analysis assistant.

    Analyze the following document and produce the following structured output:

    1. Title of the document
    2. Type of document (article, essay, report, etc.)
    3. Authors
    4. Summary with depth: {depth}
    5. Main ideas (list of 3–6 items)
    6. Key concepts (list of 5–10 items)
    7. Conclusions
    8. {num_questions} comprehension questions. For each question include:
        - number
        - type (comprehension, reflection, analysis, application)
        - difficulty (easy, medium, hard)
        - question
        - suggested answer

    Document content:
    -----------------
    {text}

    """

    # Llamada al modelo de qroq

    response = client.chat.completions.create(
        model = "mixtral-8x7b-32768",

        messages = [
            {"role" : "system", "content" : "You are an expert academic evaluator."},
            {"role" : "user", "content" : prompt}
        ],
        temperature=0.3,
    )

    # Obtener el texto generado

    output = response.choices[0].message["content"]

    questions = [
        Question(
            number=i + 1,
            q_type="comprehension",
            difficulty="medium",
            question=f"Example question {i+1}",
            suggested_answer="Example answer."
        )
        for i in range(num_questions)
    ]

    return AcademicAnalysis(
        document_title="Generated by Groq",
        document_type="Unknown",
        authors="Unknown",
        summary=output,  # Aquí va el texto generado por Groq
        main_ideas=["Idea 1", "Idea 2"],
        key_concepts=["Concept 1", "Concept 2"],
        conclusions="Generated conclusion.",
        questions=questions
    )