import os
import json
from dotenv import load_dotenv
from groq import Groq
from app.models.academic_model import AcademicAnalysis, Question

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))


def safe_json_loads(text: str):
    """
    Intenta cargar JSON. Si falla, intenta reparar el texto.
    """
    try:
        return json.loads(text)
    except:
        # Intento de reparación básica
        try:
            start = text.find("{")
            end = text.rfind("}") + 1
            cleaned = text[start:end]
            return json.loads(cleaned)
        except:
            raise ValueError("Groq no devolvió JSON válido:\n" + text)


def evaluate_document(text: str, depth: str, num_questions: int) -> AcademicAnalysis:
    """
    Evalúa un documento académico usando Groq y devuelve un análisis estructurado.
    """

    prompt = f"""
    You are an expert academic evaluator. Analyze the following document:

    --- DOCUMENT CONTENT ---
    {text}
    ------------------------

    Depth level: {depth}
    Number of questions: {num_questions}

    Provide the output STRICTLY in valid JSON with the following structure:

    {{
        "summary": "...",
        "main_objectives": ["...", "..."],
        "main_ideas": ["...", "..."],
        "key_points": ["...", "..."],
        "insights": ["...", "..."],
        "questions": [
            {{
                "number": 1,
                "q_type": "comprehension",
                "difficulty": "medium",
                "question": "...",
                "suggested_answer": "..."
            }}
        ]
    }}

    RULES:
    - Do NOT add explanations.
    - Do NOT add markdown.
    - Do NOT add text before or after the JSON.
    - Only return VALID JSON.
    """

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {"role": "system", "content": "You are an expert academic evaluator."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.3,
    )

    raw_output = response.choices[0].message.content

    # Intentar cargar JSON de forma segura
    data = safe_json_loads(raw_output)

    # Construcción de preguntas
    questions = [
        Question(
            number=q.get("number", 0),
            q_type=q.get("q_type", ""),
            difficulty=q.get("difficulty", ""),
            question=q.get("question", ""),
            suggested_answer=q.get("suggested_answer", "")
        )
        for q in data.get("questions", [])
    ]


    # Construcción del análisis final
    return AcademicAnalysis(
        document_title="Generated by Groq",
        summary=data.get("summary", ""),
        main_objectives=data.get("main_objectives", []),
        main_ideas=data.get("main_ideas", []),
        key_points=data.get("key_points", []),
        insights=data.get("insights", []),
        conclusions=data.get("conclusions", ""),
        authors=data.get("authors", []),
        questions=questions
    )